import { Inter } from "next/font/google";
import "./globals.css";
import NavigationMenuDemo from "@/components/shared/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <nav>
        <NavigationMenuDemo />
      </nav>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
